[tool.ruff]
target-version = "py310"
select = [
  "F",
  "E",
  "W",
  "C",
  "B",
  "I",
  "YTT",
  "ASYNC",
  "RUF",
  "AIR",
  "NPY",
  "C4",
  "T10",
  "EXE",
  "ISC",
  "ICN",
  "RSE",
  "TCH",
  "TID",
  "INT",
  "PLE",
  # "FIX",
  # "A",
  # "T20",
  # "S",
  # "PL",
]
exclude = [
  "/usr/lib",
	"extensions",
  "extensions-builtin",
  "modules/lora",
  "modules/dml",
  "modules/models/diffusion",
]
ignore = [
	"A003", # Class attirbute shadowing builtin
	"C901", # Function is too complex
	"E501", # Line too long
	"E731", # Do not assign a `lambda` expression, use a `def`
	"I001", # Import block is un-sorted or un-formatted
	"W605", # Invalid escape sequence, messes with some docstrings
  "B905", # Without explicit scrict
  "C408", # Rewrite as a literal
  "E402", # Module level import not at top of file
  "E721", # Do not compare types, use `isinstance()`
  "F401", # Imported but unused
  "EXE001", # Shebang present
  "ISC003", # Implicit string concatenation
  "RUF005", # Consider concatenation
  "RUF012", # Mutable class attributes
  "RUF013", # Implict optional
  "RUF015", # Prefer `next`
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.security.HTTPBasic"]

[tool.pytest.ini_options]
base_url = "http://127.0.0.1:7860"
